---
- hosts: prelim_arena_1
  remote_user: swarmie

  vars_prompt:
    - name: "team"
      prompt: "Enter the team's code"
      private: no

  tasks:
    - name: reboot robots
      command: reboot
      become: yes
      async: 0
      poll: 0

    - name: wait for robots to reboot
      wait_for: >
        host="{{inventory_hostname}}"
        port=22
        delay=15
        timeout=60
      delegate_to: localhost

    - name: remove existing rover_workspace
      file: path=/home/swarmie/rover_workspace state=absent

    - name: move {{team}}'s archive to home directory
      command: cp /home/swarmie/physicalTeams2017/Swarmathon-{{team}} /home/swarmie/Swarmathon-{{team}}
